version: "3.7"

services:
  app:
    build:
      args:
        user: cheefa
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: chefaa-task
    container_name: chefaa-task
    restart: unless-stopped
    working_dir: /var/www/
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - chefaa-task

  db:
    image: mysql:5.7
    container_name: chefaa-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql/:/var/lib/mysql
    networks:
      - chefaa-task

  nginx:
    image: nginx:1.17-alpine
    container_name: chefaa-task-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - chefaa-task

networks:
  chefaa-task:
    driver: bridge


